guacamole/src/main/webapp/app/client/controllers/clientController.js, guacamole/src/main/webapp/app/client/directives/guacFileTransfer.js, guacamole/src/main/webapp/app/client/directives/guacFileTransferManager.js, guacamole/src/main/webapp/app/client/styles/transfer-manager.css, guacamole/src/main/webapp/app/client/styles/transfer.css, guacamole/src/main/webapp/app/client/templates/client.html, guacamole/src/main/webapp/app/client/templates/guacFileTransfer.html, guacamole/src/main/webapp/app/client/templates/guacFileTransferManager.html, guacamole/src/main/webapp/app/client/types/ManagedClient.js, guacamole/src/main/webapp/app/element/directives/guacFocus.js, guacamole/src/main/webapp/app/element/directives/guacMarker.js, guacamole/src/main/webapp/app/element/directives/guacUpload.js, guacamole/src/main/webapp/app/element/types/Marker.js, guacamole/src/main/webapp/translations/en_US.json
I temporarily removed file transfer support for the sake of developing GUAC-963, but this change puts that all back.
The UI for file transfer is significantly different now:
* The list of files being uploaded/downloaded is shown in the menu, not via notifications.
* A new "upload" button has been added, allowing file uploads on platforms which lack drag/drop.
* The menu will automatically show when file transfers are initiated, and the file transfer section will automatically scroll into view.
=> GUAC-963: Restore file transfer support (again)

guacamole/src/main/webapp/app/client/styles/client.css
Also need to set client-body to height 100% for it to work in Firefox
=> GUAC-980 Client does not properly size itself in Firefox

guacamole/src/main/webapp/app/client/directives/guacClient.js
Use $evalAsync instead of $apply to avoid digest in progress error.
=> GUAC-978 Digest in progress error when loading connection in FF/Win7

guacamole/src/main/webapp/app/client/controllers/clientController.js, guacamole/src/main/webapp/app/notification/directives/guacNotification.js, guacamole/src/main/webapp/app/notification/types/NotificationAction.js, guacamole/src/main/webapp/app/notification/types/NotificationCountdown.js
Errors during connect were not being shown because ```showStatus()``` will only have an effect if no status is currently visible. Automatic reconnect was failing because the countdown object provided was defined via a JavaScript object, not an instance of ```NotificationCountdown```, and thus lacked the ```performAction()``` function.
=> GUAC-981: Fix handling of errors. Fix handling of auto-reconnect.

guacamole/src/main/webapp/app/osk/styles/osk.css
Without relative positioning, the resize sensor inside the div fills the entire screen, intercepting all mouse and touch events, possibly preventing the OSK from ever being hidden.
=> GUAC-982: Containing div of the OSK resize-sensor must have relative positioning.

guacamole/src/main/webapp/app/client/controllers/clientController.js, guacamole/src/main/webapp/app/home/controllers/homeController.js, guacamole/src/main/webapp/app/home/templates/home.html, guacamole/src/main/webapp/app/index/controllers/indexController.js, guacamole/src/main/webapp/app/index/styles/loading.css, guacamole/src/main/webapp/app/login/controllers/loginController.js, guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js, guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js, guacamole/src/main/webapp/app/manage/controllers/manageController.js, guacamole/src/main/webapp/app/manage/controllers/manageUserController.js, guacamole/src/main/webapp/app/manage/templates/manage.html, guacamole/src/main/webapp/app/manage/templates/manageConnection.html, guacamole/src/main/webapp/app/manage/templates/manageConnectionGroup.html, guacamole/src/main/webapp/app/manage/templates/manageUser.html
This change removes the caching of permissions from the index controller, explicitly loads permissions wherever needed, and delays display of UI components until most data is loaded (the "manage" button may appear after a delay otherwise).
As it became a nuisance while fixing this, I've also modified the handling of routing events such that status dialogs are *always* hidden upon navigation.
=> GUAC-975: Fix permission handling

extensions/guacamole-auth-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLConnection.java, extensions/guacamole-auth-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLConnectionGroup.java, guacamole/src/main/webapp/app/manage/controllers/manageController.js
This change modifies the MySQL auth such that it consistently uses its own "ROOT" identifier to refer to the root connection group. It doesn't matter whether a particular auth provider uses "ROOT" to refer to the root group, but whatever identifier it uses must be consistent.
Prior to this change, the MySQL auth would return ```null``` as the parent identifier of connections in root, while also rejecting ```null``` when used to search for connection groups.
This change also fixes an issue in the initialization of ```$scope``` variables in the manage controller, noticed during testing.
=> GUAC-964: Ensure connections and connection groups only refer to the root group as "ROOT"

guacamole/pom.xml, guacamole/src/main/webapp/app/index/indexModule.js, guacamole/src/main/webapp/lib/angular-touch.js
This change adds [ngTouch](https://docs.angularjs.org/api/ngTouch) such that we benefit from their touch-aware ngClick implementation. For this to work, an [open issue regarding jQuery compatibility](https://github.com/angular/angular.js/issues/2548) needed to be addressed. I kept my changes within the coding style of the ngTouch source.
=> GUAC-970: Add and fix ngTouch.

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/GuacamoleSession.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/properties/BasicGuacamoleProperties.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/auth/TokenRESTService.java, guacamole/src/main/webapp/app/auth/service/authenticationService.js, guacamole/src/main/webapp/app/index/config/indexRouteConfig.js
This change restores a feature present in all past Guacamole releases:
URL parameters and any available request data (cookies, SSL certs, etc.) are made available to the auth provider with each request, and the user's session may be created or updated based on the validity of that data.
=> GUAC-971: Restore secondary authentication

guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/Connection.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/ConnectionGroup.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/User.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/simple/SimpleAuthenticationProvider.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connectiongroup/ConnectionGroupRESTService.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/user/UserRESTService.java
This change removes usage of null identifiers via ```SimpleAuthenticationProvider```, which ultimately affects NoAuth, adding documentation to guacamole-ext noting that identifiers/usernames cannot be null.
Permission filtering is also fixed here, having been partially re-broken via GUAC-1000. ```List``` query parameters are translated to an empty list when unspecified; they are not ```null```.
=> GUAC-1001: Do not use null identifiers

guacamole/src/main/webapp/app/client/directives/guacViewport.js, guacamole/src/main/webapp/app/client/templates/guacClient.html
This change alters the scroll compensation algorithm used by the ```guacViewport``` directive such that it works with both iOS 7 and iOS 8.
Since scroll events are not always sent by iOS, a low-load polling timer has been added, too.
After much fiddling, I've managed to determine that the text input UI was invisible on iOS 7 because Safari erroneously determines that the ```iframe``` resize sensor obscures it. This change works around that by rearranging the DOM of the ```guacClient``` directive such that the resize sensor is somewhat deeper.
The strange miscalculations seem to be related to ```display: table```.
:bug: :beetle: :bee: :ant:
=> GUAC-956: Fix display and text input rendering on iOS 7.

guacamole/src/main/webapp/app/client/styles/menu.css, guacamole/src/main/webapp/app/client/styles/viewport.css
iOS 7 has some major issues with rendering ```position: fixed``` elements, particularly when the native on-screen keyboard has been shown. The entire page shifts almost completely out of view when the device is rotated, and touch events register the wrong coordinates.
Since there are no elements in the content of the client view that affect document flow, it's safe to use a combination of ```position: absolute``` and the ```guacViewport``` directive instead.
=> GUAC-1043: Do not rely on fixed positioning for client viewport.

guacamole/src/main/webapp/app/client/directives/guacClient.js, guacamole/src/main/webapp/app/client/directives/guacThumbnail.js, guacamole/src/main/webapp/app/client/templates/guacClient.html, guacamole/src/main/webapp/app/client/templates/guacThumbnail.html, guacamole/src/main/webapp/app/osk/directives/guacOsk.js, guacamole/src/main/webapp/app/osk/templates/guacOsk.html
The previous attempt worked, but caused a regression in window resize handling, as the resize sensor would not always be tied to window size at that position in the DOM.
The new attempt replaces each ```iframe``` resize sensor with an ```object``` resize sensor. iOS 7 seems to render these ones properly.
=> GUAC-958: Yet another attempt at a workaround for the iOS 7 visibility issue.

doc/guacamole-example/pom.xml, doc/guacamole-example/src/main/webapp/index.html
Hello!
The provided example was not working, so I've added some fixes. After that I was able to successfully run the example on jetty9 for 'ssh' protocol.
Best regards,
Vasily
=> GUAC-1046: Fix of doc/guacamole-example

guacamole-common-js/src/main/webapp/modules/Keyboard.js, guacamole/src/main/webapp/app/client/controllers/clientController.js
On Firefox, and probably other browser/system combinations, Shift+Alt is translated to Shift+Meta, and thus cannot be used when showing the Guacamole menu. This change allows Meta to be used in place of Alt when showing the menu, thus avoiding confusion.
The Guacamole keyboard also contained a bug which caused different keysyms to be returned depending on whether Meta was pressed or released, mainly due to Meta having the same JavaScript keycode as Alt. This change modifies the Guacamole keyboard event interpretation algorithm such that the keysym used for keydown is preferred when interpreting keyup.
=> GUAC-998: Fix handling of Guacamole menu with respect to Meta

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connection/ConnectionRESTService.java
Jersey doesn't like ```List<? extends X>```, but it loves ```List<X>```.
=> GUAC-1051: Ensure getConnectionHistory() returns a List with a well-defined type.

LICENSE, doc/guacamole-example/pom.xml, extensions/guacamole-auth-ldap/pom.xml, extensions/guacamole-auth-mysql/pom.xml, extensions/guacamole-auth-noauth/pom.xml, guacamole-common-js/pom.xml, guacamole-ext/pom.xml, guacamole/pom.xml, pom.xml
In preparation for the 0.9.5 release, this change bumps the version numbers of all changed guacamole-client components.
The only completely unchanged component is guacamole-common.
=> GUAC-1018: Bump version to 0.9.5.

guacamole-common-js/src/main/webapp/modules/Version.js
=> GUAC-1018: Bump version in Version.js of guacamole-common-js (incorrect since 0.9.4).

guacamole/src/main/webapp/app/client/styles/client.css, guacamole/src/main/webapp/app/client/styles/menu.css, guacamole/src/main/webapp/app/client/templates/client.html, guacamole/src/main/webapp/app/home/templates/guacRecentConnections.html, guacamole/src/main/webapp/app/home/templates/home.html, guacamole/src/main/webapp/app/manage/templates/manageConnection.html, guacamole/src/main/webapp/index.html
IE10 has many issues with ```display: table```. Thankfully, it supports an older version of the CSS flexbox recommendation, which is a better choice anyway.
Not-so-thankfully, old versions of Firefox are riddled with issues when it comes to flexbox layouts. I've managed to work around these by either ensuring that children with complex layouts use flexbox as well, and removing ```position: absolute``` where possible.
In general, the changes were:
1. Use flexbox and the old browser-specific versions of flexbox instead of ```display: table```, because IE10 has issues with ```display: table```.
2. Use flexbox instead of ```width: 100%``` and find other ways to style percentage-driven components within the menu, as old Firefox miscalculates percentage dimensions of child elements within a …
=> GUAC-1052: Make compatible with IE10 and ancient Firefox by pulling teeth.

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connection/ConnectionRESTService.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connectiongroup/ConnectionGroupRESTService.java
Moving connections or groups via REST was not working. Turns out I'm not setting the parent identifier on update for either of those objects.
=> GUAC-1100: Update parent identifier within REST service calls.

guacamole/src/main/webapp/app/groupList/directives/guacGroupList.js, guacamole/src/main/webapp/app/groupList/types/GroupListItem.js
The location chooser is still slow despite pagination, as it always has exactly one item in the root level, and thus is never paginated.
As nearly all of its contents are connections that will not be shown anyway, this change omits connections from the group list hierarchy entirely if no connection template is provided to the ```guacGroupList``` directive.
=> GUAC-1099: Do not attempt to display connections in guacGroupList if no connection template is provided.

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connectiongroup/ConnectionGroupRESTService.java
```connectionGroupDirectory.get()``` might return null. The retrieval service should be used so that an exception containing a reasonable error code is thrown instead.
=> GUAC-1108: Use retrieval service for retrieving connection groups. Avoid possible NPE.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/UserMapper.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/UserService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/user/UserMapper.xml
From [GUAC-1109](https://glyptodon.org/jira/browse/GUAC-1109):
> Unfortunately, MySQL versions older than 5.5.5 do not have the ```SHA2()```
> function that we now depend on for testing user credentials. This includes the
> version of MySQL currently installed on deployments of CentOS 6.
>
> Using the latest JDBC auth code on an older MySQL will result in the following
> error:
>
> ``` FUNCTION guacamole.SHA2 does not exist ```
>
> We need to migrate back to handling hashing and salting purely within Java.
=> GUAC-1109: Do not rely on SHA2(). Handle password hashing in Java.

guacamole/src/main/webapp/app/index/services/authenticationInterceptor.js
The modified logic was flawed because the only requests that reach the interceptor are REST API requests. If we explicitly exclude those, then we exclude everything and there is no redirect.
What we should have done is redirect **only** authentication requests (requests to ```/api/tokens```), and **only** if we aren't already on the login page.
=> GUAC-1119: Redirect to login ONLY for requests to /api/tokens, and ONLY if not already at login.

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connection/APIConnectionRecord.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connection/ConnectionRESTService.java
The connection history REST endpoint was returning the ```ConnectionRecord``` list exactly as retrieved from the auth provider. As the JSON serializer determines the resulting JSON through reflection, this can result in the response containing internal data.
In the case of [GUAC-1121](https://glyptodon.org/jira/browse/GUAC-1121), this resulted in the response containing the ```user```/```currentUser``` cyclic references.
Thankfully, it looks like no other REST endpoints within Guacamole directly expose guacamole-ext objects. They all return API-specific objects instead.
=> GUAC-1121: Do not expose retrieved ConnectionRecord list directly.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/AuthenticatedUser.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/auth/TokenRESTService.java
During the great 0.9.4 rewrite, support for the X-Forwarded-For header was accidentally removed, along with logging of authentication failures.
This change restores that support, and also adds support for X-Forwarded-For to the JDBC auth, such that it reports the proper remote host of clients behind proxies, assuming the header was not forged.
As with our old support for X-Forwarded-For, it is known and acknowledged that this information may be false. It is used for logging purposes only, and the data is validated enough that only valid IPv4 and IPv6 addresses can be present.
=> GUAC-1135: Restore support for X-Forwarded-For.

guacamole/src/main/webapp/app/list/types/FilterPattern.js, guacamole/src/main/webapp/app/list/types/FilterToken.js, guacamole/src/main/webapp/app/list/types/IPv4Network.js, guacamole/src/main/webapp/app/list/types/IPv6Network.js
Rather than match the entire pattern string against each object property, this change matches individual whitespace-separated tokens against each object property. For an object to match the pattern, every token must match at least one property.
Searching for "guacadmin vnc", "guacadmin    vnc", and "vnc guacadmin" are all equivalent.
=> GUAC-1138: Add filter pattern tokenizer.

guacamole/src/main/webapp/app/client/styles/menu.css, guacamole/src/main/webapp/app/client/templates/client.html, guacamole/src/main/webapp/app/home/controllers/homeController.js, guacamole/src/main/webapp/app/home/templates/home.html, guacamole/src/main/webapp/app/index/config/indexRouteConfig.js, guacamole/src/main/webapp/app/index/indexModule.js, guacamole/src/main/webapp/app/login/controllers/loginController.js, guacamole/src/main/webapp/app/login/loginModule.js, guacamole/src/main/webapp/app/manage/templates/manageConnection.html, guacamole/src/main/webapp/app/manage/templates/manageConnectionGroup.html, guacamole/src/main/webapp/app/manage/templates/manageConnections.html, guacamole/src/main/webapp/app/manage/templates/manageSessions.html, guacamole/src/main/webapp/app/manage/templates/manageUser.html, guacamole/src/main/webapp/app/manage/templates/manageUsers.html, guacamole/src/main/webapp/app/navigation/directives/guacUserMenu.js, guacamole/src/main/webapp/app/navigation/navigationModule.js, guacamole/src/main/webapp/app/navigation/services/userPageService.js
This change adds the user menu to the Guacamole menu. As the user menu is always determined by the current user, the technically-unnecessary ```rootGroup``` and ```permissions``` attributes/parameters are removed from both the user menu and the page service.
Given some future caching of REST results, I believe this makes sense. Our existing services rely on dependency injection to avoid such parameter passing. Why not then rely on some similar sort of "data injection" via service calls?
=> GUAC-1126: Add user menu to Guacamole menu

guacamole/src/main/webapp/app/auth/service/authenticationService.js, guacamole/src/main/webapp/app/client/services/guacClientManager.js, guacamole/src/main/webapp/app/login/controllers/loginController.js, guacamole/src/main/webapp/app/login/loginModule.js
To avoid unexpected behavior due to in-memory active clients and multiple valid auth tokens, Guacamole should perform the following upon login:
1. Clear any managed clients, such that no connections remain active in memory
2. Invalidate the existing auth token, if any
=> GUAC-1126: Automatically clear connections and auth tokens upon login (fixes GUAC-1066).

guacamole/src/main/webapp/app/auth/authModule.js, guacamole/src/main/webapp/app/auth/service/authenticationService.js, guacamole/src/main/webapp/app/client/services/guacClientManager.js, guacamole/src/main/webapp/app/login/controllers/loginController.js, guacamole/src/main/webapp/app/login/loginModule.js, guacamole/src/main/webapp/app/rest/services/cacheService.js
A minor change for sake of separation of concerns, this removes the need for the authentication service to "know" what other services need to be updated/cleared when a user's session is ending. Instead, generic ```guacLogin``` and ```guacLogout``` events are broadcast on the root scope.
Services, etc. which need to ensure data is destroyed upon logout (or upon login) can listen for these events and act accordingly.
=> GUAC-1126: Maintain session-local data through login/logout events

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/activeconnection/ActiveConnectionPermissionService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/activeconnection/ActiveConnectionService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/activeconnection/TrackedActiveConnection.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/tunnel/GuacamoleTunnelService.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/ActiveConnection.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/activeconnection/ActiveConnectionRESTService.java, guacamole/src/main/webapp/app/groupList/directives/guacGroupList.js, guacamole/src/main/webapp/app/groupList/types/GroupListItem.js, guacamole/src/main/webapp/app/home/templates/connection.html, guacamole/src/main/webapp/app/manage/templates/connection.html, guacamole/src/main/webapp/app/rest/types/ActiveConnection.js
Rather than use the ```activeConnections``` property of connections and groups from ```/api/connectionGroups/*/tree```, which may be cached, instead query ```/api/activeConnections``` within the ```guacGroupList``` directive.
This requires:
1. Modifying the permissions checks of the database auth to display provide active connection info about connections you can ```READ```
2. Updating documentation to describe most properties of active connections as optional / ```null``` if unknown
3. Modifying the UI code to pull all this new information from the active connection service, and map it into place via a dynamically-set getter
=> GUAC-1126: Calculate active connections using the active connection service

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/APIRequest.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/auth/TokenRESTService.java
As described in [GUAC-1102](https://glyptodon.org/jira/browse/GUAC-1102), JAX-RS / Jersey consume the entire HTTP request, causing future calls to ```getParameter()``` to simply return ```null```. This breaks the functionality of some authentication providers, as well as the ```Credentials``` object in general.
We can work around this by gathering all request parameters into a ```MultivaluedMap```, and providing access to those parameters through a wrapper
=> GUAC-1102: Reconstitute consumed HTTP requests with an external collection of parameter name/value pairs.

guacamole-common/src/main/java/org/glyptodon/guacamole/servlet/GuacamoleHTTPTunnelServlet.java
The tunnel is currently not explicitly closed in all cases when end-of-stream is encountered. If the connection closes between requests, the tunnel may never be explicitly closed, and the client will never detect the end-of-stream condition, even though the underlying socket is not open.
=> GUAC-1096: Properly close() and cleanup HTTP tunnel when end-of-stream is encountered.

guacamole/src/main/webapp/app/form/directives/form.js, guacamole/src/main/webapp/app/form/directives/formField.js, guacamole/src/main/webapp/app/form/formModule.js, guacamole/src/main/webapp/app/form/styles/form-field.css, guacamole/src/main/webapp/app/form/styles/form.css, guacamole/src/main/webapp/app/form/templates/form.html, guacamole/src/main/webapp/app/form/templates/formField.html, guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js, guacamole/src/main/webapp/app/manage/directives/connectionParameter.js, guacamole/src/main/webapp/app/manage/styles/connection-parameter.css, guacamole/src/main/webapp/app/manage/templates/connectionParameter.html, guacamole/src/main/webapp/app/manage/templates/manageConnection.html, guacamole/src/main/webapp/app/rest/types/Field.js, guacamole/src/main/webapp/app/rest/types/FieldOption.js, guacamole/src/main/webapp/app/rest/types/Protocol.js, guacamole/src/main/webapp/translations/en_US.json
This change generalizes the protocol-specific ```ProtocolParameter``` and ```guacConnectionParameter``` into ```FormField``` and ```guacFormField```. An arbitrary array of ```FormField``` objects can be placed onto any page through the ```guacForm``` directive, which will retrieve and set field values into a provided model object.
=> GUAC-1106: Create generalized form module and directives

guacamole/src/main/webapp/app/form/directives/form.js, guacamole/src/main/webapp/app/form/styles/form.css, guacamole/src/main/webapp/app/form/templates/form.html, guacamole/src/main/webapp/app/manage/templates/manageConnection.html, guacamole/src/main/webapp/app/rest/types/Field.js, guacamole/src/main/webapp/app/rest/types/Form.js
This change allows the ```guacForm``` directive to accept not only an array of ```Field``` objects, but also a ```Form``` or ```Form[]```. The ```Form``` object is newly-defined, and simply pairs a set of fields with a name and title. Accepting ```Form[]``` allows for splitting forms into sub-forms, each with corresponding headers.
The logic which handles converting all these types to a common ```Form[]``` for the sake of the template is generic enough that it will actually also accept a single ```Field```, and the directive documentation has been updated to reflect this. Doing so is almost equivalent to simply using ```guacFormField```, except that the field will be encased in the various elements that make up a form.
=> GUAC-1160: Add support for form sections

guacamole/src/main/webapp/app/settings/services/preferenceService.js
This reverts commit 21d3e45. Having the keyboard pop open automatically proved disruptive.
=> GUAC-1053: Default to "none" input mode as before.

guacamole/src/main/webapp/app/index/config/indexTranslationConfig.js, guacamole/src/main/webapp/app/locale/services/translationLoader.js, guacamole/src/main/webapp/app/settings/services/preferenceService.js
The previous language selection code would default to whichever language is chosen by ```$translate```, which is configured to always use "en_US", ignoring the user's preferences. The value of the preference would only take effect when the user goes to the preferences screen.
This change:
1. Infers the default language by checking the browser language
2. Configures "en_US" as the fallback for any missing strings
3. Uses a custom translation loader, such that "en_US" will be used as the fallback if the file for the preferred language does not exist
=> GUAC-1053: Fix language defaults

guacamole/src/main/webapp/app/form/directives/formField.js
The typed value should be the coerced version of the model value ... not ```field.value```, which is specific to ```BOOLEAN``` fields and **does not contain the current value of a field**.
=> GUAC-1179: Fix handling of numeric fields

guacamole-common-js/src/main/webapp/modules/AudioChannel.js, guacamole-common-js/src/main/webapp/modules/Keyboard.js, guacamole/src/main/webapp/app/element/directives/guacResize.js, guacamole/src/main/webapp/app/element/templates/blank.html, guacamole/src/main/webapp/index.html
This change resolves the simpler of the outstanding browser warnings:
1. ```keyLocation``` is deprecated
2. ```webkitAudioContext``` is deprecated
3. Charset not declared within first 1024 bytes of each HTML file
Firefox also fell victim to a ```$rootScope:inprog``` error, as it sometimes handles resize events synchronously, resulting in a digest loop. This change switches over to using ```$evalAsync()``` instead of ```$apply()``` for that particular case.
=> GUAC-1170: Fix basic JavaScript warnings.

doc/guacamole-example/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml, extensions/guacamole-auth-jdbc/pom.xml, extensions/guacamole-auth-jdbc/src/main/assembly/dist.xml, extensions/guacamole-auth-ldap/pom.xml, extensions/guacamole-auth-ldap/src/main/assembly/dist.xml, extensions/guacamole-auth-noauth/pom.xml, extensions/guacamole-auth-noauth/src/main/assembly/dist.xml, guacamole-common-js/pom.xml, guacamole-common/pom.xml, guacamole-ext/pom.xml, guacamole/pom.xml, pom.xml, project-assembly.xml
This change fixes all Maven warnings that occurred during the build, namely:
1. Missing plugin versions
2. Weird multiple .jar artifacts for the guacamole-auth-jdbc-* projects (for example: "Replacing pre-existing project main-artifact file: target/guacamole-auth-jdbc-postgresql-0.9.6.jar with assembly file: target/extension/guacamole-auth-jdbc-postgresql-0.9.6.jar")
3. Filename length warnings in the source .tar.gz (only extensions to .tar provide the long names we need)
=> GUAC-1170: Fix all Maven warnings

guacamole/src/main/webapp/app/osk/styles/osk.css, guacamole/src/main/webapp/app/textInput/styles/textInput.css
The OSK has been untouched with respect to style for years, and the text input interface stands in contrast to the rest of the guac UI.
This change cleans up the OSK style, and restyles text input to match:
=> GUAC-1170: Clean up OSK style while it's relevant

guacamole/src/main/webapp/app/client/styles/menu.css, guacamole/src/main/webapp/app/client/templates/client.html, guacamole/src/main/webapp/app/index/styles/buttons.css, guacamole/src/main/webapp/app/settings/styles/buttons.css
This pull request solves two problems encountered when theming Guacamole:
1. Menu section headers and content are not associated with each other such that both the header and the content of a particular section can be selectively modified.
2. Background images are set directly on buttons, causing issues if overriding CSS needs to apply an image to the button (such as a gradient).
=> GUAC-587: Make DOM/CSS friendlier for theming

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/resource/AbstractResource.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/resource/ClassPathResource.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/resource/Resource.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/resource/ResourceServlet.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/resource/SequenceResource.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/resource/WebApplicationResource.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/resource/package-info.java
This change adds (but does not use) support for serving arbitrary resources defined by an implementation of the `Resource` interface.
To leverage this support, you must register an instance of `ResourceServlet` via Guice. For example, to serve the resource "/foo/bar.txt", from within the classpath, at "/some/place/blah.txt", you would write something like:
```java
serve("/some/place/blah.txt").with(new ResourceServlet(new ClassPathResource("text/plain", "/foo/bar.txt")));
```
If the resource is within the webapp already, you can do that, too:
```java
serve("/some/place/blah.txt").with(new ResourceServlet(new WebApplicationResource(getServletContext(), "/foo/bar.txt")));
```
Or dynamically concatenate resources as one logical resource:
```java
serve("/some/place/doubleblah.txt").with(new …
```
=> GUAC-587: Implement support for serving of arbitrary resources.

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/AuthenticationProviderFacade.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/Extension.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionModule.java
There are two major problems with the new extension system:
1. If `GUACAMOLE_HOME/extensions` is missing, startup proceeds, but `app.js` and `app.css` are not generated (bug).
2. If an authentication provider fails to load, users will get confusing stacktraces and Guice creation errors, not meaningful log messages.
This change addresses these issues by:
1. Ensuring `app.js` and `app.css` are created independently of `GUACAMOLE_HOME/extensions`.
2. Hiding the real `AuthenticationProvider` behind `AuthenticationProviderFacade` which gracefully handles instantiation errors and logs them accordingly.
=> GUAC-587: Improve loading of extensions

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/AuthenticationProviderFacade.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/Extension.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionManifest.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionModule.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/LanguageResourceService.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/language/LanguageRESTService.java
This change loads the `translations` and `resources` part of the `guac-manifest.json`, serving each dynamically within the `/translations` and `/app/ext/[NAMESPACE]/` paths respectively.
Left unimplemented for the time being is overlaying of translation JSON for multiple definitions of the same language, though the functions are documented with this future behavior in mind.
=> GUAC-587: Add support for dynamic static/translation resources

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/ModeledUser.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/UserContext.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/UserContextService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/UserModel.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en_US.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.7.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/user/UserMapper.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.7.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/user/UserMapper.xml, guacamole-ext/src/main/java/org/glyptodon/guacamole/form/Form.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/Connection.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/ConnectionGroup.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/User.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/UserContext.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/simple/SimpleUserContext.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/schema/SchemaRESTService.java, guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js, guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js, guacamole/src/main/webapp/app/manage/controllers/manageUserController.js, guacamole/src/main/webapp/app/manage/styles/attributes.css, guacamole/src/main/webapp/app/manage/templates/manageConnection.html, guacamole/src/main/webapp/app/manage/templates/manageConnectionGroup.html, guacamole/src/main/webapp/app/manage/templates/manageUser.html, guacamole/src/main/webapp/app/rest/services/schemaService.js
This change adds a "disabled" attribute to the user object provided by the JDBC auth, and a corresponding column to the `guacamole_user` table. The necessary strings for the new admin section and field are provided by a translation string overlay within the JDBC auth.
Disabled users cannot log in, even though their account technically exists. Attempts to log in as a disabled user are rejected as if the provided credentials were invalid.
=> GUAC-800: Allow explicit disable/enable of user accounts.

guacamole-ext/src/main/resources/org/glyptodon/guacamole/protocols/rdp.json
Lacking the `value` property, `BOOLEAN` parameters do not work as expected. They behave as if `undefined` indicates the parameter is enabled, and thus appear checked by default, yet neither the checked or unchecked states have any effect on the parameters of the connection.
=> GUAC-1218: Provide "value" property for "BOOLEAN" parameters.

guacamole-ext/src/main/java/org/glyptodon/guacamole/form/Field.java, guacamole/src/main/webapp/app/form/controllers/checkboxFieldController.js, guacamole/src/main/webapp/app/form/controllers/numberFieldController.js, guacamole/src/main/webapp/app/form/controllers/passwordFieldController.js, guacamole/src/main/webapp/app/form/controllers/selectFieldController.js, guacamole/src/main/webapp/app/form/directives/formField.js, guacamole/src/main/webapp/app/form/services/formService.js, guacamole/src/main/webapp/app/form/templates/checkboxField.html, guacamole/src/main/webapp/app/form/templates/formField.html, guacamole/src/main/webapp/app/form/templates/numberField.html, guacamole/src/main/webapp/app/form/templates/passwordField.html, guacamole/src/main/webapp/app/form/templates/selectField.html, guacamole/src/main/webapp/app/form/templates/textAreaField.html, guacamole/src/main/webapp/app/form/templates/textField.html, guacamole/src/main/webapp/app/form/types/FieldType.js
This change adds support for registering custom field types through `formService`, which accepts `FieldType` objects describing the template and optional controller associated with that field type. The field type controller (or template) must then use the documented properties on `$scope` to render the field and manipulate its value.
All existing field types have been migrated to this new mechanism, and the `formService` supports dynamic registration of new types via the `registerFieldType()` function.
=> GUAC-1176: Implement support for custom field types

guacamole/doc/example/guacamole.properties
The example `guacamole.properties` is no longer relevant, as Guacamole no longer requires `guacamole.properties` to work and provides defaults for everything.
=> GUAC-1221: Remove old guacamole.properties example

guacamole/pom.xml, guacamole/src/main/webapp/lib/messageformat/nl.js, guacamole/src/main/webapp/translations/en.json, guacamole/src/main/webapp/translations/nl.json
@nrbrt has contributed a Dutch translation of the Guacamole interface via pull request #201. This pull request squashes those commits into a single commit, updates language names for consistency, and adds the required messageformat.js locale.
I went ahead and removed the country code from the English translation, too. It's the only language with a country code in the name, and it only serves as a point of confusion. There's no other English to choose at the moment.
=> GUAC-1238: Merge contributed Dutch translation

guacamole-common-js/src/main/webapp/modules/Client.js, guacamole-common-js/src/main/webapp/modules/JSONReader.js, guacamole-common-js/src/main/webapp/modules/Object.js
This change adds support for Guacamole protocol objects as `Guacamole.Object`. Only one object type is currently supported, a filesystem, which is exposed to developers via the `onfilesystem` handler.
From the received `Guacamole.Object`, developers may call `requestInputStream()` to request the creation of an input stream, or `createOutputStream()` to create an output stream, each referring to the stream by name (as Guacamole protocol objects are essentially sets of named streams). A callback function can be provided to `requestInputStream()` to easily handle the resulting input stream "body". Alternatively, the received input stream body can be handled at a lower level via the `onbody` handler.
As future use of objects will require reading JSON from input streams, included in these …
=> GUAC-1172: Add Guacamole.Object and support for related instructions

guacamole-common-js/src/main/webapp/modules/Mouse.js
The changes from #207 do seem to solve the problem, but introduce the following issues:
1. 100 millisecond latency between the mouse scroll wheel click and response via Guacamole.
2. Over-emphasis of small scroll events for devices which use true smooth scrolling, and actually provide real pixel values in `e.delta`.
I have built off the changes from #207 replacing the use of a timer with better constants derived from the delta values used by Firefox and Chrome. The key change introduced through #207, resetting `scroll_delta` after a series of scrolls is applied, remains.
The primary driving factor behind missed scroll events was that `e.delta` does not necessarily evenly divide into `scrollThreshold`, leading to accumulating error.
=> GUAC-1244: Ensure small scroll events are handled

guacamole-common-js/src/main/webapp/modules/Tunnel.js
As described by David Borth in [GUAC-1084](https://glyptodon.org/jira/browse/GUAC-1084):
> When using ChainedTunnel, each time 'connect' is called, the first tunnel is removed from the tunnels  list and used for connection
> Next time we want to connect (after disconnect) to the same ChainedTunnel, it will try to consume again a fresh tunnel from the list of remaining tunnels - what will cause it to fail if list is empty
> 
> Bottom line - the number of tunnels ChainedTunnel is initialized with, is the max number 'connect' execution would work
This change contains the contribution from #82, along with some minor clarifying changes to the comment describing `committedTunnel`.
=> GUAC-1084: Support re-use of a single ChainedTunnel instance

guacamole-common-js/src/main/webapp/modules/Tunnel.js
This change adds support for CORS to `Guacamole.HTTPTunnel` through the changes from #80. The only changes added to #80 by this specific PR are:
1. Clarification of the additional `Guacamole.HTTPTunnel` constructor parameter.
2. Squashing of the commit-revert-commit-commit (which was really intended as a single commit) into the single commit it should have been.
=> GUAC-1083: Allow use of CORS with Guacamole.HTTPTunnel

guacamole/pom.xml, guacamole/src/main/webapp/lib/messageformat/de.js, guacamole/src/main/webapp/translations/de.json
This change merges the German translation contributed by Sven Thuma. In addition, I've performed the usual changes:
1. Removed the country code from the language name.
2. Added the missing messageformat.js locale file.
I've also gone ahead and translated the pluralized words, which were left in English in the original submission. I assume they were simply forgotten, or the format was unfamiliar. I'm relatively confident that my German is not so horrible that I did this wrong, but it's *is* possible.
=> GUAC-1255: Merge German translation from Sven Thuma.

guacamole/src/main/webapp/app/login/styles/login.css
[GUAC-1249](https://glyptodon.org/jira/browse/GUAC-1249) ("Labels do not show on login page in IE 11") appears to result from IE11 not properly creating a new stacking context for the `position: relative` field `<div>`. Lacking a new stacking context, the `z-index: -1` property of the placeholder `<span>` forces the placeholder below other opaque page elements, rendering the placeholder permanently invisible.
Explicitly forcing a new stacking context by applying `z-index: 1` to the parent `<div>` solves the issue without risking violating standard behavior.
See: http://www.w3.org/TR/CSS21/visuren.html#propdef-z-index
=> GUAC-1249: Ensure stacking context of login UI fields is explicit.

guacamole/src/main/webapp/translations/it.json
This change adds the Italian translation contributed by Serena Soldati via [GUAC-1241](https://glyptodon.org/jira/browse/GUAC-1241).
The translation appears to be incomplete, and is missing quite a few connection parameters, etc., but is complete enough that average users will have a fully-Italian experience. Administrators wanting Italian will be half disappointed.
The original contribution was in ISO-8859-1 with DOS line endings. I have converted to UTF-8 and UNIX prior to committing the translation on Serena's behalf.
=> GUAC-1241: Add Italian translation

guacamole-ext/src/main/resources/org/glyptodon/guacamole/protocols/vnc.json, guacamole/src/main/webapp/translations/de.json, guacamole/src/main/webapp/translations/en.json, guacamole/src/main/webapp/translations/fr.json, guacamole/src/main/webapp/translations/it.json, guacamole/src/main/webapp/translations/nl.json, guacamole/src/main/webapp/translations/ru.json
This change follows the change made in glyptodon/guacamole-server#59, adding the new `clipboard-encoding` parameter to the JSON describing the parameters available for the VNC protocol.
=> GUAC-298: Add VNC parameter for clipboard encoding.

guacamole-ext/src/main/resources/org/glyptodon/guacamole/protocols/ssh.json, guacamole-ext/src/main/resources/org/glyptodon/guacamole/protocols/telnet.json, guacamole/src/main/webapp/translations/en.json
This change adds UI support for the `color-scheme` parameter added to SSH and telnet via glyptodon/guacamole-server#61. Per usual, I'm only adding English strings. My German isn't that great, and I don't know the other supported languages at all.
=> GUAC-1195: Add "color-scheme" parameter to SSH and telnet.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/ModeledUser.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/UserModel.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/UserService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.8.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/user/UserMapper.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.8.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/user/UserMapper.xml
This change implements the date/time restrictions required by [GUAC-1213](https://glyptodon.org/jira/browse/GUAC-1213), while avoiding the user interface coding that has been blocking us for so long.
The logic, etc. here all works... we now just need to make things pretty. The user attributes are all stubbed out as text fields.
=> GUAC-1213: Add date/time restrictions for user accounts.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/ModeledUser.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/form/DateField.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/form/Field.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/form/TimeField.java, guacamole/src/main/webapp/app/form/controllers/dateFieldController.js, guacamole/src/main/webapp/app/form/controllers/timeFieldController.js, guacamole/src/main/webapp/app/form/services/formService.js, guacamole/src/main/webapp/app/form/templates/dateField.html, guacamole/src/main/webapp/app/form/templates/timeField.html, guacamole/src/main/webapp/app/rest/types/Field.js, guacamole/src/main/webapp/translations/en.json
This change adds `DATE` and `TIME` field types which leverage HTML5's date and time input types. For browsers that do not provide support for those input types, placeholders are provided as a formatting guide.
=> GUAC-1213: Add support for date/time fields.

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connection/ConnectionRESTService.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connectiongroup/ConnectionGroupRESTService.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/user/UserRESTService.java
The default mimetype, declared at the REST service level, would be `application/json`. This causes a parse error in Chrome and Firefox when the response is not actually valid JSON.
See: https://glyptodon.org/jira/browse/GUAC-1294
=> GUAC-1294: Use mimetype text/plain for REST endpoints which return plain strings.

guacamole/src/main/webapp/app/form/controllers/dateFieldController.js, guacamole/src/main/webapp/app/form/controllers/timeFieldController.js, guacamole/src/main/webapp/app/form/directives/guacLenientDate.js, guacamole/src/main/webapp/app/form/directives/guacLenientTime.js, guacamole/src/main/webapp/app/form/templates/dateField.html, guacamole/src/main/webapp/app/form/templates/timeField.html
Browsers without support for the HTML5 `date` and `time` input fields will render those fields as `text`. Angular's default parsing for such fields is very strict, and the formatting does not perfectly match our placeholders.
This change implements lenient parsing for dates and times, and modifies the formatting to match what the user is expected to enter. Just about all reasonable date/time strings are accepted, while invalid strings are interpreted as blank.
The parsing splits the date/time string into groups, year/month/day for dates and hour/minute/second for times, provides default values for any missing groups, and coerces parsed values into expected ranges. If the time includes an AM or PM designation, that is interpreted leniently as well... "12 aardvark" would be interpreted …
=> GUAC-1213: Provide lenient date/time parsing

guacamole-common-js/src/main/webapp/modules/Client.js, guacamole-common-js/src/main/webapp/modules/DataURIReader.js, guacamole-common-js/src/main/webapp/modules/Display.js
The `img` instruction is intended to replace `png` and `jpeg` as the means of sending image updates. Support for `png` and `jpeg` remain present in `Guacamole.Client`, but `img` is now available as an alternative.
Recent experimental changes to guacamole-server use only `img` for updates, replacing core functions like `guac_protocol_send_png()` with alternatives like `guac_client_stream_png()` which leverage `img`.
As `img` uses the streaming subsystem, it allows the server to stream image data during the encoding process (rather than encoding and buffering the entire image prior to sending), reducing  latency.
=> GUAC-240: Add support for experimental "img" instruction

guacamole/src/main/webapp/app/client/controllers/clientController.js, guacamole/src/main/webapp/app/client/directives/guacFileBrowser.js, guacamole/src/main/webapp/app/client/styles/file-browser.css, guacamole/src/main/webapp/app/client/styles/file-transfer-dialog.css, guacamole/src/main/webapp/app/client/templates/guacFileBrowser.html, guacamole/src/main/webapp/app/client/types/ManagedFileDownload.js, guacamole/src/main/webapp/app/client/types/ManagedFileUpload.js
The Guacamole file browser currently suffers from the following usability issues:
1. Files download and the current directory changes when files are clicked. Double click is more intuitive.
2. The file transfer dialog can be hidden behind the file browser on smaller screens.
3. The contents of the file browser does not properly refresh after an upload completes.
These changes address the above (and avoid issues with double-click handling on mobile devices) through the following:
1. Clicking a file focuses that file, but performs no other action.
2. Clicking a *focused* file performs the action associated with that file, such as initiating a download or changing the current directory, and then de-focuses the file.
3. The file browser is automatically refreshed when any upload completes, or …
=> GUAC-1293: Improve file browser usability

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/connection/ConnectionModel.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/connection/ModeledConnection.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/connectiongroup/ConnectionGroupModel.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/connectiongroup/ModeledConnectionGroup.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/tunnel/ConfigurableGuacamoleTunnelService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/ModeledUser.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/user/UserContext.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/en.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/001-create-schema.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/upgrade/upgrade-pre-0.9.8.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/connection/ConnectionMapper.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/connectiongroup/ConnectionGroupMapper.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/001-create-schema.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/schema/upgrade/upgrade-pre-0.9.8.sql, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/connection/ConnectionMapper.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/connectiongroup/ConnectionGroupMapper.xml, guacamole-ext/src/main/java/org/glyptodon/guacamole/form/DateField.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/form/NumericField.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/form/TimeField.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/form/TimeZoneField.java, guacamole/src/main/webapp/app/form/controllers/numberFieldController.js
This change adds concurrency policy columns (max connections / max connections per user) to the schema for connections and connection groups, adds mappings for those columns to properties in the model objects, and exposes those values as attributes to the web application.
Additionally, the following bugs were noticed and fixed during testing:
1. One of the connection error messages which was copied from the connection group section still said "connection group" instead of "connection".
2. The logic of `tryAdd()` was flawed when the maximum is zero (unlimited), and would universally deny additional values.
3. The test for whether a numeric field is blank within the web application UI was overly broad, and considered "0" to be a blank value, as it's falsy.
Connections | Connection Groups …
=> GUAC-830: Implement concurrency policy attributes

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLAuthenticationProvider.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLGuacamoleProperties.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/glyptodon/guacamole/auth/postgresql/PostgreSQLAuthenticationProvider.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/glyptodon/guacamole/auth/postgresql/PostgreSQLGuacamoleProperties.java
This change adds four new concurrency properties for the database auth, replacing the old "duplicate" and "simultaneous" properties. The old properties are still supported, but using them will result in warnings in the logs, along with suggestions for replacing them.
1. `mysql-default-max-connections`
2. `mysql-default-max-group-connections`
3. `mysql-default-max-connections-per-user`
4. `mysql-default-max-group-connections-per-user`
1. `postgresql-default-max-connections`
2. `postgresql-default-max-group-connections`
3. `postgresql-default-max-connections-per-user`
4. `postgresql-default-max-group-connections-per-user`
For example, if you set `postgresql-disallow-simultaneous-connections: false` within `guacamole.properties`, you will now see the following log messages:
```
WARN …
```
=> GUAC-830: Add new concurrency properties.

extensions/guacamole-auth-ldap/pom.xml, extensions/guacamole-auth-ldap/src/main/java/net/sourceforge/guacamole/net/auth/ldap/LDAPAuthenticationProvider.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/AuthenticationProviderService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/ConfigurationService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/EscapingService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/LDAPAuthenticationProviderModule.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/LDAPGuacamoleProperties.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/connection/ConnectionService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/user/AuthenticatedUser.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/user/UserContext.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/user/UserService.java, guacamole-ext/src/main/java/org/glyptodon/guacamole/net/auth/simple/SimpleUser.java
This change just about completely rewrites the LDAP authentication, adding support for listing users as well as connections, using Guice for ease of development.
Lacking this, it will not be possible to use the admin UI to associate LDAP accounts with MySQL / PostgreSQL data, as those accounts would not be visible.
In the case of LDAP auth, it is up to the LDAP directory to decide whether the bound user can query all users, and which users will be visible to such a query.
=> GUAC-586: Support listing users within LDAP authentication

guacamole/src/main/webapp/app/navigation/services/userPageService.js
As `userPageService` is a service which is initialized possibly before the user even logs in, it is not valid to store the available data sources at the service level. They should instead be pulled as needed.
=> GUAC-586: Services must not store stale auth data.

doc/guacamole-example/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json, extensions/guacamole-auth-jdbc/pom.xml, extensions/guacamole-auth-ldap/pom.xml, extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json, extensions/guacamole-auth-noauth/pom.xml, extensions/guacamole-auth-noauth/src/main/resources/guac-manifest.json, guacamole-common-js/pom.xml, guacamole-ext/pom.xml, guacamole/pom.xml, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionModule.java, pom.xml
Bumping version for the 0.9.8 release. The only component that didn't change within guacamole-client is guacamole-common. The following should ALL be bumped:
1. guacamole-client
2. guacamole
3. guacamole-common-js
3. guacamole-ext
4. guacamole-auth-jdbc (MySQL and PostgreSQL modules, too)
5. guacamole-auth-ldap
6. guacamole-auth-noauth
With the recent changes in 0.9.7 regarding `guac-manifest.json` and the `guacamoleVersion` property, we have to bump the versions within each `guac-manifest.json`, not just `pom.xml`, as well as within `ExtensionModule` (the class that checks that value).
=> GUAC-1280: Bump version numbers to 0.9.8 where appropriate.

guacamole-common-js/src/main/webapp/modules/AudioChannel.js, guacamole-common-js/src/main/webapp/modules/Client.js
Audio latency currently increases without bound when underflow occurs. There is no mechanism compensating for lag in audio playback.
This change uses frame boundaries (`sync` instructions) as a baseline for measuring audio latency, defining latency as the amount of audio remaining to be played at the beginning of a new frame. The starting time of future audio packets is rescheduled as necessary to keep this latency within the duration of a frame.
=> GUAC-427: Limit audio latency with respect to graphical frames

guacamole-common-js/src/main/webapp/modules/Keyboard.js
From [GUAC-1322](https://glyptodon.org/jira/browse/GUAC-1322):
> If a keyup event is received for an unknown key (no corresponding keysym), all keys are released as a fallback. This is good, but it also clears the event log, causing `interpret_event()` within `Guacamole.Keyboard` to return `undefined` instead of the handled event (or `null`), ultimately causing the event interpreter to throw an exception:
> 
> ![defaultprevented-error](https://cloud.githubusercontent.com/assets/4632905/9697721/22ff083e-534e-11e5-8f3d-25e3b89e319a.png)
This change fixes `interpret_event()` such that it always returns the interpreted event, as required by its definition, or `null` if no event is interpreted. It must *never* return `undefined`.
=> GUAC-1322: Fix Guacamole.Keyboard keyup fallback

guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js, guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js, guacamole/src/main/webapp/app/manage/directives/locationChooser.js, guacamole/src/main/webapp/app/manage/templates/locationChooser.html, guacamole/src/main/webapp/app/manage/templates/manageConnection.html, guacamole/src/main/webapp/app/manage/templates/manageConnectionGroup.html
The location chooser directive was not updated to use the updated `guacGroupList`. This fixes it.
=> GUAC-1334: Fix the horribly-broken location chooser

extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/AuthenticationProviderService.java
=> GUAC-1350: Invalid logins should not result in "insufficient credentials" exceptions.

guacamole-common/src/main/java/org/glyptodon/guacamole/protocol/ConfiguredGuacamoleSocket.java, guacamole-common/src/main/java/org/glyptodon/guacamole/protocol/GuacamoleClientInformation.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/TunnelRequest.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/TunnelRequestService.java, guacamole/src/main/webapp/app/client/services/guacImage.js, guacamole/src/main/webapp/app/client/types/ManagedClient.js
This change adds a promise-based version of the `guacImage` service - a service which was originally introduced within #246, a PR which is being split into smaller pieces such that the WEBP-specific changes can be separate.
=> GUAC-1305: Add image mimetypes to Guacamole protocol handshake.

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionModule.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/LanguageResourceService.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/properties/BasicGuacamoleProperties.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/properties/StringSetProperty.java, guacamole/src/main/webapp/app/locale/services/translationLoader.js
This change adds a new `allowed-languages` property which restricts the languages used within the web application. The value of this property is a comma-separated list of language keys.
If specified, languages whose keys are not within the `allowed-languages` list will not be used by the translation service (even if explicitly requested), and will not be listed as choices within the preferences screen, though the original JSON will remain accessible via direct HTTP.
=> GUAC-1345: Restrict available languages if explicitly configured

guacamole/src/main/webapp/app/client/styles/file-transfer-dialog.css, guacamole/src/main/webapp/app/client/templates/guacFileTransferManager.html
Currently, the file transfer dialog will expand without limit as additional files are transferred, eventually extending beyond the bounds of the browser viewport. As the transfer dialog is anchored to the bottom of the viewport, and the "clear" button is on the top of the dialog, it becomes impossible to clear the transferred files and restore visibility.
These changes limit the maximum height of the file transfer dialog such that it is does not exceed 3in height, 1.5in height, or the full height of the browser window, whichever yields the best fit.
=> GUAC-1349: Ensure file transfer dialog does not overflow viewport bounds.

guacamole/src/main/webapp/app/settings/directives/guacSettingsConnectionHistory.js
Sorting mainly by username for historical records is just silly. The records should default to being sorted chronologically, with the most recent records first.
=> GUAC-1193: Fix the history sort order

guacamole/src/main/webapp/app/navigation/services/userPageService.js, guacamole/src/main/webapp/app/settings/directives/guacSettingsConnectionHistory.js, guacamole/src/main/webapp/app/settings/templates/settingsConnectionHistory.html
This change fixes two usability issues with the new history search interface:
1. *ALL* users were given access to the history list, not only admins. This is technically fine from a security perspective, as visibility is always limited to only those records related to objects they can `READ`, but it's not what we meant.
2. The entire search table hides during searches. When the search takes a second or two, this is very disconcerting. It is better if only the table body is hidden - the header should remain.
=> GUAC-1193: Improve history search usability

guacamole-common-js/src/main/webapp/modules/Client.js, guacamole-common-js/src/main/webapp/modules/Display.js, guacamole-common-js/src/main/webapp/modules/VideoPlayer.js
This change adds base support for video streaming, analogous to the true audio streaming support added recently. No specific support for any video codecs is added, however an API for playing video via custom codec handlers is now present. Such handlers are given access to the destination layer, and can thus do just about anything for rendering, including leveraging hardware support.
The type used to represent the layer is `Guacamole.Display.VisibleLayer`. This used to be `LayerContainer` many releases ago, but was changed when the Guacamole display was refactored. I fixed the old references to this non-existent class as well.
=> GUAC-1354: Add support for video streaming

extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/AuthenticationProviderService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/ConfigurationService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/LDAPAuthenticationProviderModule.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/LDAPConnectionService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/LDAPGuacamoleProperties.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/StringListProperty.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/connection/ConnectionService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/user/UserService.java
The current Guacamole LDAP integration relies on being able to directly derive the a user's DN from their username. This will not work if the user's username is not part of their DN, as is often the case with Active Directory, or if users are not all within the same base DN.
This change alters the DN derivation algorithm such that the user DN can be determined through a search against the LDAP directory, in the case that service credentials are provided for Guacamole to do so (via `ldap-search-bind-dn` and `ldap-search-bind-password`).
The semantics of the existing `ldap-username-attribute` property have also been altered such that a comma-separated list of attributes can be specified. If multiple username attributes are provided, each will be used by Guacamole when determining possible …
=> GUAC-1115: Add support for complex LDAP directory layouts

guacamole/src/main/webapp/app/client/services/guacVideo.js
The handling of video has changed in Guacamole, and thus we no longer need to check `canPlayType(https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType)` of [`HTMLVideoElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement). We can just use `Guacamole.VideoPlayer.getSupportedTypes()`.
Removing use of `canPlayType()` fixes [GUAC-1375](https://glyptodon.org/jira/browse/GUAC-1375) - a bug which surfaces when MS EDGE does not define `canPlayType` for the `video` element.
A similar change was made for audio via 324c800 (part of PR #272) for [GUAC-1354](https://glyptodon.org/jira/browse/GUAC-1354)
=> GUAC-1375: Use Guacamole.VideoPlayer.getSupportedTypes() instead of canPlayType()

extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/connection/ConnectionService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/user/UserContext.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/user/UserService.java
Guacamole 0.9.8 was released with a regression in its LDAP support, where parameter tokens would not be handled for connections defined within LDAP. They are, however, properly handled if those connections are stored within MySQL or PostgreSQL. This change restores the use of parameter tokens within LDAP.
During testing, I configured my LDAP directory within `guacamole.properties` incorrectly, and ran across the following warning: "Cannot directly derive user DN when multiple username attributes are specified". The way to resolve this is to specify a search DN, but that is not obvious from the warning, and there is no reason the warning should not be more specific. I went ahead and clarified that warning before creating this PR.
=> GUAC-1342: Restore use of parameter tokens within LDAP

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/JDBCAuthenticationProviderModule.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/JDBCEnvironment.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/connection/ModeledConnection.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/connectiongroup/ModeledConnectionGroup.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/tunnel/ConfigurableGuacamoleTunnelService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/tunnel/RestrictedGuacamoleTunnelService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLAuthenticationProvider.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLAuthenticationProviderModule.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLEnvironment.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLGuacamoleProperties.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/glyptodon/guacamole/auth/postgresql/PostgreSQLAuthenticationProvider.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/glyptodon/guacamole/auth/postgresql/PostgreSQLAuthenticationProviderModule.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/java/org/glyptodon/guacamole/auth/postgresql/PostgreSQLEnvironment.java
This change moves the handling of the JDBC auth properties (both MySQL and PostgreSQL) into a new `JDBCEnvironment` class, extended as `MySQLEnvironment` and `PostgreSQLEnvironment` respectively.
This allows configuration information to be exposed to anything injected with `JDBCEnvironment`, removing the need to pass tons of parameters to the constructors of services being configured for injection within Guice modules.
=> GUAC-1373: Refactor JDBC auth properties into own class

guacamole/src/main/webapp/app/groupList/directives/guacGroupListFilter.js, guacamole/src/main/webapp/app/groupList/templates/guacGroupListFilter.html, guacamole/src/main/webapp/app/home/controllers/homeController.js, guacamole/src/main/webapp/app/home/styles/home.css, guacamole/src/main/webapp/app/home/templates/home.html, guacamole/src/main/webapp/app/settings/directives/guacSettingsConnections.js, guacamole/src/main/webapp/app/settings/templates/settingsConnections.html, guacamole/src/main/webapp/translations/de.json, guacamole/src/main/webapp/translations/en.json, guacamole/src/main/webapp/translations/fr.json, guacamole/src/main/webapp/translations/it.json, guacamole/src/main/webapp/translations/nl.json, guacamole/src/main/webapp/translations/ru.json
This change adds a new filtering directive, `guacGroupListFilter`, which functions almost identically to `guacFilter` except that it handles connection group hierarchies automatically and appropriately (rather than simply filtering an array).
`guacGroupListFilter` accepts a the same type of inputs as `guacGroupList` and `guacFilter`. By default, with no search string specified, the hierarchy is passed through untouched. Once a search string is specified, the hierarchy is flattened such that **all** connections and connection groups appear at the root level. The hierarchy within all nested connection groups is fully preserved, with nested connections and groups duplicated as necessary.
=> GUAC-1406: Implement connection filtering within admin UI and home screen

extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/ConfigurationService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/EncryptionMethod.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/EncryptionMethodProperty.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/LDAPConnectionService.java, extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/LDAPGuacamoleProperties.java
As described in [GUAC-1166](https://glyptodon.org/jira/browse/GUAC-1166), this change adds support for encryption of LDAP connections using SSL/TLS (LDAPS) or STARTTLS. This is configured by setting the new `ldap-encryption-method` property to `ssl` or `starttls` respectively. The default value of this property is `none`, which yields unencrypted LDAP connections.
For the SSL/TLS/STARTTLS connection to succeed, the cert(s) required to verify the certificate chain must be present in either the Java default trust store or within an application-specific trust store specified with the `javax.net.ssl.trustStore` system property.
Since the default port is different for LDAPS, the handling of the `ldap-port` property has been modified to select the appropriate default, either 389 or 636, …
=> GUAC-1166: Add support for SSL/TLS and STARTTLS to LDAP.

guacamole-common-js/jsdoc-conf.json, guacamole-common-js/src/main/webapp/modules/AudioPlayer.js, guacamole-common-js/src/main/webapp/modules/Client.js, guacamole-common-js/src/main/webapp/modules/DataURIReader.js, guacamole-common-js/src/main/webapp/modules/Display.js, guacamole-common-js/src/main/webapp/modules/InputStream.js, guacamole-common-js/src/main/webapp/modules/IntegerPool.js, guacamole-common-js/src/main/webapp/modules/JSONReader.js, guacamole-common-js/src/main/webapp/modules/Keyboard.js, guacamole-common-js/src/main/webapp/modules/Layer.js, guacamole-common-js/src/main/webapp/modules/Mouse.js, guacamole-common-js/src/main/webapp/modules/Namespace.js, guacamole-common-js/src/main/webapp/modules/Object.js, guacamole-common-js/src/main/webapp/modules/OnScreenKeyboard.js, guacamole-common-js/src/main/webapp/modules/OutputStream.js, guacamole-common-js/src/main/webapp/modules/Status.js, guacamole-common-js/src/main/webapp/modules/StringReader.js, guacamole-common-js/src/main/webapp/modules/StringWriter.js, guacamole-common-js/src/main/webapp/modules/Tunnel.js, guacamole-common-js/src/main/webapp/modules/Version.js
Our JSDoc-generated documentation has suffered from at least the following issues:
1. Inner variables and functions were included in the public documentation, even though they are not accessible nor useful at the API level ([`Guacamole.OnScreenKeyboard`](http://guac-dev.org/doc/0.9.8/guacamole-common-js/symbols/Guacamole.OnScreenKeyboard.html) was particularly bad).
2. The JSDoc syntax was for an older version of JSDoc, preventing us from upgrading to JSDoc 3.
This change fixes those issues, brings the comment and code style in the vicinity of those changes up to date (as much as reasonably possible), and adds a new `jsdoc-conf.json` file for convenient JSDoc generation. Assuming JSDoc is installed, the documentation can now be generated simply by running:
$ jsdoc -c jsdoc-conf.json …
=> GUAC-791: Fix JSDoc comments and upgrade to JSDoc 3.

doc/guacamole-example/src/main/java/org/glyptodon/guacamole/net/example/DummyGuacamoleTunnelServlet.java, guacamole-common/doc/example/ExampleTunnelServlet.java, guacamole-common/src/main/java/org/glyptodon/guacamole/servlet/GuacamoleHTTPTunnel.java, guacamole-common/src/main/java/org/glyptodon/guacamole/servlet/GuacamoleHTTPTunnelMap.java, guacamole-common/src/main/java/org/glyptodon/guacamole/servlet/GuacamoleHTTPTunnelServlet.java, guacamole-common/src/main/java/org/glyptodon/guacamole/servlet/GuacamoleSession.java
Background
----------------
Guacamole the web application uses [the `createTunnel()` function of `TunnelRequestService`](https://github.com/glyptodon/guacamole-client/blob/91f8f5b06b6ffa2e410cef13e7178f94c19478e7/guacamole/src/main/java/org/glyptodon/guacamole/net/basic/TunnelRequestService.java#L309-L357) to parse the HTTP request received when the JavaScript client is connecting. This is true for both `Guacamole.HTTPTunnel` and `Guacamole.WebSocketTunnel`.
The `createTunnel()` function commits resources and actually establishes the connection to guacd. This means `createTunnel()` is also the point at which the underlying extension will insert its own hooks into the returned `GuacamoleTunnel` to handle connection cleanup - for example, the way the database auth overrides `close()`.
If …
=> GUAC-1427: Ensure HTTP tunnels cannot become stuck.

doc/guacamole-example/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json, extensions/guacamole-auth-jdbc/pom.xml, extensions/guacamole-auth-ldap/pom.xml, extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json, extensions/guacamole-auth-noauth/pom.xml, extensions/guacamole-auth-noauth/src/main/resources/guac-manifest.json, guacamole-common-js/pom.xml, guacamole-common-js/src/main/webapp/modules/Version.js, guacamole-common/pom.xml, guacamole-ext/pom.xml, guacamole/pom.xml, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionModule.java, pom.xml
This time, **all projects were modified**, thus everything gets bumped. Absolutely all `pom.xml` should now say `0.9.9` for their versions. Same goes for `guacamoleVersion` within `guac-manifest.json` and `Guacamole.API_VERSION` within guacamole-common-js.
=> GUAC-1392: Bump Guacamole version to 0.9.9.

guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
Seems our logic was wrong after all. We should be checking `$scope.userExists()`, not whether `username` is defined.
=> GUAC-1407: Do not show "Clone" button if source user does not yet exist.

guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
As established in the existing account page logic ([lines 490 - 493 of `manageUserController.js`](https://github.com/glyptodon/guacamole-client/blob/9b933b75203c2f3dc9a81f07671bf09d2dbd5fdb/guacamole/src/main/webapp/app/manage/controllers/manageUserController.js#L490-L493)):
```javascript
// Account is not relevant if it does not exist and cannot be
// created
if (!linked && readOnly)
return;
```
we should only add account pages which are relevant. In the case of a cloned user, only the selected data source is relevant. Restricting the account pages to a single possibility effectively hides the account tabs due to the logic built into the `<guac-page-list>` directive.
=> GUAC-1407: Do not show irrelevant account tabs when cloning.

guacamole-common-js/src/main/webapp/modules/Client.js
If we do not properly delete past streams when closed, future attempts to create streams having the same index may erroneously use the previous stream object, resulting in strange concatenation effects.
=> GUAC-1452: Input streams must be invalidated when closed.

guacamole/src/main/webapp/translations/fr.json
ERROR_TUNNEL_303 contains a typo because "paramètre" is plural and needs a "s" at the end (like ERROR_TUNNEL_308)
=> GUAC-1459 Fix typo in french translation

guacamole-ext/src/main/java/org/glyptodon/guacamole/token/StandardTokens.java
As described in [GUAC-1451](https://glyptodon.org/jira/browse/GUAC-1451), this change adds the new `GUAC_DATE` and `GUAC_TIME` tokens which allow server-local timestamps to be inserted arbitrarily within connection parameter values. Since these tokens are handled within `addStandardTokens()`, any code using the `StandardTokens` class will automatically inherit support for these tokens, including all official authentication backends.
Additional changes were required to make `addStandardTokens()` reasonable in the case that a `Credentials` object does not apply, and to make `StandardTokens` match its own definition.
=> GUAC-1451: Add support for GUAC_DATE and GUAC_TIME tokens.

guacamole-ext/src/main/resources/org/glyptodon/guacamole/protocols/rdp.json, guacamole/src/main/webapp/translations/en.json
Corresponding parameter and value declaration for the keymap added via glyptodon/guacamole-server#98.
=> GUAC-1410: Add parameter and value translation string for Japanese keymap.

guacamole/src/main/webapp/app/client/controllers/clientController.js, guacamole/src/main/webapp/app/client/directives/guacClient.js
Changes to the clipboard were previously communicated through both `guacClipboard` events and a scope watch on the `clipboardData` property. Since both the Guacamole menu and the `guacClient` directive can modify that property, this meant it was impossible to distinguish between clipboard changes made by the user (via the menu) and clipboard changes made by `guacClient` (due to received remote clipboard data). Received clipboard data from the remote side was thus being echoed back as if the user had entered it themselves again.
This change changes the semantics of the `clipboardData` property such that it can be used **ONLY** for reading the current clipboard state. Desired changes to the clipboard must be communicated by `guacClipboard` events, which only the `guacClient` directive shall …
=> GUAC-1480: Fix handling of clipboard changes.

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/Extension.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionManifest.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionModule.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/PatchResourceService.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/RESTServiceModule.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/patch/PatchRESTService.java, guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/patch/package-info.java, guacamole/src/main/webapp/app/index/config/templateRequestDecorator.js, guacamole/src/main/webapp/app/rest/services/cacheService.js, guacamole/src/main/webapp/app/rest/services/patchService.js
This change allows HTML "patches" to be specified within `guac-manifest.json` under the `html` property, similar to the existing `css` and `js` properties already used for CSS and JavaScript files respectively.
Each specified HTML file within `guac-manifest.json` is automatically exposed to the JavaScript side of the web application through a REST service. The JavaScript driving the UI then automatically applies these patches to the HTML as it is loaded.
The HTML patches are simply HTML fragments containing additional `meta` tags that dictate how the patch is to be applied. Each tag is of the form `<meta name="NAME" content="SELECTOR">` where `NAME` is one of the names listed below and `SELECTOR` is a CSS selector:
Name Attribute      | Description
-------------------|----------------- …
=> GUAC-1378: Allow modification of HTML via extensions

guacamole-docker/bin/start.sh
This change backports the updates from upstream [GUACAMOLE-99](https://issues.apache.org/jira/browse/GUACAMOLE-99) and [GUACAMOLE-100](https://issues.apache.org/jira/browse/GUACAMOLE-100), which add support for the `GUACD_HOSTNAME`, `GUACD_PORT`, and `GUACAMOLE_HOME` environment variables to the Guacamole Docker image.
=> ALAC-32: Backport Docker updates from upcoming 0.9.11-incubating to our stable 0.9.10.

guacamole-common-js/src/main/webapp/modules/Parser.js, guacamole-common-js/src/main/webapp/modules/Tunnel.js, guacamole/src/main/webapp/app/touch/directives/guacTouchDrag.js
This PR merges several upstream changes which fix typos and incorrect JavaScript usage which could result in unexpected behavior. Specifically:
* apache/incubator-guacamole-client#126 ([GUACAMOLE-229](https://issues.apache.org/jira/browse/GUACAMOLE-229))
* apache/incubator-guacamole-client#154 ([GUACAMOLE-295](https://issues.apache.org/jira/browse/GUACAMOLE-295))
* apache/incubator-guacamole-client#155 ([GUACAMOLE-294](https://issues.apache.org/jira/browse/GUACAMOLE-294))
=> GLYP-34: Merge upstream JavaScript cleanup changes.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserMapper.xml
See: https://issues.apache.org/jira/browse/GUACAMOLE-395
=> GLEN-104: Backport fix for missing "expired" column mapping.

guacamole/src/main/webapp/app/clipboard/services/clipboardService.js, guacamole/src/main/webapp/app/clipboard/styles/clipboard.css, guacamole/src/main/webapp/app/index/controllers/indexController.js
This change backports the changes from upstream [GUACAMOLE-128](https://issues.apache.org/jira/browse/GUACAMOLE-128) and [GUACAMOLE-310](https://issues.apache.org/jira/browse/GUACAMOLE-310), both of which deal with clipboard failures due to IE behavior.
GUACAMOLE-310 additionally addresses incorrect stripping of newline characters when the "Clipboard Permission Manager" extension is used under Chrome.
=> GLEN-102: Address IE-related clipboard issues

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/resources/translations/es.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json, guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json, guacamole/src/main/webapp/translations/en.json, guacamole/src/main/webapp/translations/es.json
These changes backport the recently-added upstream support for Brazilian, Spanish, Turkish-Q, and UK English keyboards, as well as a Spanish translation for the Guacamole web interface. All changes should be identical to upstream, with the exception of the Spanish translation which needed minor changes to resolve conflicts (GLEN 1.x does not have SQL Server support).
NOTE: There is no change specific to adding the Spanish keyboard layout to the connection parameter values. It was apparently added as part of the Spanish translation.
=> GLEN-109: Backport Spanish translation and support for new keymaps.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
From [GLEN-125](https://glyptodon.org/jira/browse/GLEN-125):
> The user account "disabled" flag implemented by the MySQL and PostgreSQL support is intended to disable access to that account, behaving as if the account is entirely absent. With the changes made by upstream [GUACAMOLE-284](https://issues.apache.org/jira/browse/GUACAMOLE-284) (backported via [GLEN-37](https://glyptodon.org/jira/browse/GLEN-37)), this behavior is broken, and disabled users are able to log in. Such users are denied access to absolutely everything (they are given a blank home screen), but authentication still succeeds.
This has been fixed upstream via [GUACAMOLE-529](https://issues.apache.org/jira/browse/GUACAMOLE-529), which is the source of the changes backported here.
=> GLEN-125: Backport fix for MySQL/PostgreSQL "disabled" flag

guacamole/src/main/webapp/app/client/controllers/clientController.js, guacamole/src/main/webapp/app/client/types/ManagedClient.js
This change forms the client-side basis of support for changing the window title in response to terminal codes received via SSH and telnet. The server-side changes, being against the guacamole-server repository, will come via a separate PR.
Relevant upstream issue: https://issues.apache.org/jira/browse/GUACAMOLE-265 ("Support OSC 0 for changing SSH/telnet window title")
=> GLEN-123: Allow protocol support to change page title

guacamole/src/main/webapp/app/rest/services/tunnelService.js, guacamole/src/main/webapp/app/rest/types/UserCredentials.js, guacamole/src/main/webapp/index.html
Relevant issues:
* [GUACAMOLE-316](https://issues.apache.org/jira/browse/GUACAMOLE-316) - "IE Compatibility mode doesn't work"
* [GUACAMOLE-347](https://issues.apache.org/jira/browse/GUACAMOLE-347) - "IE may lack window.location.origin"
* [GUACAMOLE-348](https://issues.apache.org/jira/browse/GUACAMOLE-348) - "Stream download iframe may not exist in DOM at time of removal"
=> GLEN-120: Backport upstream fixes for generally IE-specific issues

guacamole-common-js/src/main/webapp/modules/AudioRecorder.js
From upstream [GUACAMOLE-237](https://issues.apache.org/jira/browse/GUACAMOLE-237):
> [`navigator.getUserMedia()` has been deprecated within Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia), replaced by [`navigator.mediaDevices.getUserMedia()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia). See: https://www.w3.org/TR/mediacapture-streams/
Though not deprecated in the standard per se, it's clear that `navigator.getUserMedia()` is legacy. As Mozilla has marked it as deprecated within Firefox, this change will need to be made eventually to ensure forward compatibility.
{quote}
=> GLEN-119: Remove use of deprecated navigator.getUserMedia()

guacamole/pom.xml, guacamole/src/main/webapp/index.html
Commit b64091d66e01f98e4cf9b65036cccb196cfe4ad9 partly results in an unstable upgrade due to the behavior of cached copies of `app.js`. As cached JavaScript may still point to the "ngCookies" module, the webapp may fail to load with injection errors. The cache busting `?v=${project.version}` is of no help here, since the version number doesn't change during GLEN minor updates.
This change partly reverts that commit, restoring the "ngCookies" module. The module is unused by current JS, but this at least allows it to continue being available if Guacamole has been cached.
=> GLEN-126: Continue including ngCookies module for compatibility's sake.

guacamole/src/main/java/org/apache/guacamole/rest/RESTExceptionMapper.java
The build of guacamole-client for Glyptodon Enterprise is currently failing due to the changes merged via #371. This is because the backported changes (from [GUACAMOLE-566](https://issues.apache.org/jira/browse/GUACAMOLE-566)) were made in context of [GUACAMOLE-504](https://issues.apache.org/jira/browse/GUACAMOLE-504) which added a new function to `GuacamoleException` for directly retrieving the HTTP status code. That API change to `GuacamoleException` came after 0.9.12-incubating and thus is not available within GLEN 1.x.
Internally, the default implementation of the missing function is simply:
public int getHttpStatusCode() {
return getStatus().getHttpStatusCode();
}
so doing essentially the same here should satisfy the needs behind [GLEN-142](https://jira.glyptodon.org/browse/GLEN-142) …
=> GLEN-142: Retrieve HTTP status code from GuacamoleException via its associated GuacamoleStatus.

guacamole/src/main/webapp/translations/en.json, guacamole/src/main/webapp/translations/zh.json
Note that the change to `en.json` is from 9cd97eaf66a42e98940f1403cfbf0637201c621e, which was indeed part of the changes merged for [GUACAMOLE-569](https://issues.apache.org/jira/browse/GUACAMOLE-569), though not directly related to the Simplified Chinese translation.
=> GLEN-152: Add Simplified Chinese translation.

guacamole/src/main/webapp/app/index/config/httpDefaults.js
These changes reconfigure the `$http` service such that it sends additional headers to request that the browser not cache the response for GET requests, including IE.
=> GLEN-167: Backport fix for IE11 caching behavior to GLEN 1.x.

guacamole/src/main/webapp/app/index/config/httpDefaults.js
As noted on #383, these changes reconfigure the `$http` service such that it sends additional headers to request that the browser not cache the response for GET requests, including IE.
=> GLEN-167: Backport fix for IE11 caching behavior to GLEN 2.x.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledAuthenticatedUser.java, guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json, guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json, guacamole/src/main/webapp/translations/en.json
Changes relevant to issues specific to 1.x have been merged upstream for the pending 1.1.0 release. There are no corresponding issues for this in 2.x, as the base release for 2.x is 1.1.0 and thus implicitly includes these changes.
=> Bring GLEN 2.x base up-to-date with upstream staging/1.1.0.

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json, guacamole-ext/src/main/resources/org/apache/guacamole/protocols/ssh.json, guacamole/src/main/webapp/translations/en.json
This depends on #395 due to the location of the parameter definition within `ssh.json`, hence draft PR. The merge base will need to be updated to `glyptodon/1.x` once #395 is completed.
=> GLEN-162: Add definitions and translations for RDP/SSH "timezone" parameter.

guacamole/src/main/webapp/app/form/templates/form.html, guacamole/src/main/webapp/app/login/templates/login.html
As described in #398:
>
> If an element has an attribute named `disabled`, all input fields that are descendants of that element are disabled by IE regardless of the type of element the `disabled` attribute is on, even if the element is unknown. This resulted in a regression where the entire login form was disabled due to both `<guac-form-field>` and `<guac-form>` directives having an attribute named "disabled".
>
> This has since been resolved by using the alternative `data-disabled` form.
>
=> GLEN-168: Correct IE-specific regression in handling of login fields in 2.x.

guacamole/src/main/webapp/app/form/templates/form.html, guacamole/src/main/webapp/app/login/templates/login.html
If an element has an attribute named `disabled`, all input fields that are descendants of that element are disabled by IE regardless of the type of element the `disabled` attribute is on, even if the element is unknown. This resulted in a regression where the entire login form was disabled due to both `<guac-form-field>` and `<guac-form>` directives having an attribute named "disabled".
This has since been resolved by using the alternative `data-disabled` form.
=> GLEN-168: Correct IE-specific regression in handling of login fields in 1.x.

guacamole/src/main/webapp/app/client/controllers/clientController.js, guacamole/src/main/webapp/app/client/styles/connection-select-menu.css, guacamole/src/main/webapp/app/client/styles/guac-menu.css, guacamole/src/main/webapp/app/client/templates/client.html, guacamole/src/main/webapp/app/home/templates/connectionGroup.html, guacamole/src/main/webapp/app/navigation/directives/guacMenu.js, guacamole/src/main/webapp/app/navigation/services/userPageService.js, guacamole/src/main/webapp/app/navigation/styles/menu.css
This change backports upstream changes from [GUACAMOLE-723](https://issues.apache.org/jira/browse/GUACAMOLE-723) and [GUACAMOLE-822](https://issues.apache.org/jira/browse/GUACAMOLE-822) to correct the following issues noticed after the connection switching feature was backported to 1.x:
* The "Share" menu no longer closes when an option is clicked.
* The portion of the Guacamole menu containing the connection name can considerably overlap other parts of the header when the connection name is long.
* The drop down of the new connection selection menu is aligned relative to its right edge, causing the menu to overflow off the left side of the screen if the relevant part of the header is smaller than the width of the drop down.
* The connection selection menu continues to render as a drop …
=> GLEN-169: Backport connection switching fixes to 1.x.

guacamole/src/main/webapp/app/client/controllers/clientController.js, guacamole/src/main/webapp/app/client/styles/connection-select-menu.css, guacamole/src/main/webapp/app/client/styles/guac-menu.css, guacamole/src/main/webapp/app/client/templates/client.html, guacamole/src/main/webapp/app/home/templates/connectionGroup.html, guacamole/src/main/webapp/app/navigation/directives/guacMenu.js, guacamole/src/main/webapp/app/navigation/services/userPageService.js, guacamole/src/main/webapp/app/navigation/styles/menu.css
This change backports upstream changes from [GUACAMOLE-723](https://issues.apache.org/jira/browse/GUACAMOLE-723) and [GUACAMOLE-822](https://issues.apache.org/jira/browse/GUACAMOLE-822) to correct the following issues noticed after the connection switching feature was backported to 2.x:
* The "Share" menu no longer closes when an option is clicked.
* The portion of the Guacamole menu containing the connection name can considerably overlap other parts of the header when the connection name is long.
* The drop down of the new connection selection menu is aligned relative to its right edge, causing the menu to overflow off the left side of the screen if the relevant part of the header is smaller than the width of the drop down.
* The connection selection menu continues to render as a drop …
=> GLEN-169: Backport connection switching fixes to 2.x.

guacamole/src/main/webapp/app/index/filters/arrayFilter.js
The changes backported for [GLEN-169](https://jira.glyptodon.com/browse/GLEN-169) are partially broken due to a dependency on the `toArray` filter which was added upstream for [GUACAMOLE-526](https://issues.apache.org/jira/browse/GUACAMOLE-526) as part of the development required to upgrade to AngularJS 1.6.9.
The version of the `toArray` filter added with these changes is the current upstream version, effectively isolated from the following commits:
* f7ca11df5 - GUACAMOLE-526: Provide key/value pairs via toArray filter. Consistently return same array for same object.
* 2ff980ded - GUACAMOLE-526: Remove debug console.log() from toArrayFilter().
* b3eeb36b8 - GUACAMOLE-526: Update webapp to angular 1.6.9.
Other changes related to the upstream upgrade to AngularJS 1.6.9 remain omitted for …
=> GLEN-188: Backport toArray filter.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-sqlserver/src/main/resources/org/apache/guacamole/auth/jdbc/user/UserRecordMapper.xml
The ANSI SQL `POSITION()` function is not supported by SQL Server, which requires the non-standard `CHARINDEX()` function instead.
=> GLEN-206: Use CHARINDEX() rather than POSITION() within SQL Server queries.

guacamole/src/main/webapp/translations/cs.json
As noted in [GLEN-237](https://jira.glyptodon.com/browse/GLEN-237), the recently backported Czech translation was incorrect in that it should have been named `cs.json`, not `cz.json`. The incorrect naming resulted in JavaScript errors which caused the translation to fail to apply.
In addition to the naming, the translation has been updated upstream as part of the same changes. This change backports all of this.
=> GLEN-237: Backport corrections for Czech translation to 2.x.

guacamole/src/main/webapp/translations/cs.json
As noted in [GLEN-237](https://jira.glyptodon.com/browse/GLEN-237), the recently backported Czech translation was incorrect in that it should have been named `cs.json`, not `cz.json`. The incorrect naming resulted in JavaScript errors which caused the translation to fail to apply.
In addition to the naming, the translation has been updated upstream as part of the same changes. This change backports all of this.
=> GLEN-237: Backport corrections for Czech translation to 1.x.

guacamole-ext/src/main/resources/org/apache/guacamole/protocols/rdp.json, guacamole/src/main/webapp/translations/en.json
After the migration to FreeRDP 2.0.0, support for connecting directly to the console of a Hyper-V 
VM broke. This was addressed upstream via the addition of a new VMConnect-specific security mode, which is part of the changes proposed for backport in glyptodon/guacamole-server#189.
This change consists only of the parameter value and translation string for this new security mode.
=> GLEN-235: Add RDP parameter value and translation string for Hyper-V / VMConnect security mode.

extensions/guacamole-auth-duo/src/main/java/org/apache/guacamole/auth/duo/UserVerificationService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java, guacamole-ext/src/main/java/org/apache/guacamole/language/TranslatableGuacamoleClientException.java, guacamole-ext/src/main/java/org/apache/guacamole/language/TranslatableGuacamoleInsufficientCredentialsException.java
This change backports the fix for the incorrect handling of extension errors which resulted in translated error messages being rendered as raw translation keys. See:
https://jira.glyptodon.com/browse/GLEN-241
As GLEN 1.x maintains strict compatibility with 0.9.12-incubating, and only `TranslatableGuacamoleClientException` and `TranslatableGuacamoleInsufficientCredentialsException` are required by these changes, only those exceptions are backported here.
=> GLEN-241: Correct handling of translated error messages in 1.x.

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordSet.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/connection/ConnectionService.java, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.xml, extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/apache/guacamole/auth/jdbc/connection/ConnectionRecordMapper.xml
From [GLEN-262](https://jira.glyptodon.com/browse/GLEN-262):
> The database backends supported by Guacamole provide two ways of querying the connection history: a flexible, searchable query, and a query that simply retrieves all history records. As the latter is equivalent to the former with zero search criteria, upstream has combined these mechanisms for the sake of consistency and maintainability via [GUACAMOLE-1123](https://issues.apache.org/jira/browse/GUACAMOLE-1123). We should backport the same.
These changes are already on the `glyptodon/2.x` branch due to merge of all upstream 1.3.0 changes, but they need manual backporting for 1.x to maintain compatibility with 0.9.12-incubating.
=> GLEN-262: Backport standardization on single history retrieval mechanism.

extensions/guacamole-auth-cas/pom.xml, extensions/guacamole-auth-duo/pom.xml, extensions/guacamole-auth-header/pom.xml, extensions/guacamole-auth-jdbc/pom.xml, extensions/guacamole-auth-json/pom.xml, extensions/guacamole-auth-ldap/pom.xml, extensions/guacamole-auth-openid/pom.xml, extensions/guacamole-auth-quickconnect/pom.xml, extensions/guacamole-auth-radius/pom.xml, extensions/guacamole-auth-saml/pom.xml, extensions/guacamole-auth-totp/pom.xml, extensions/pom.xml, guacamole-common-js/pom.xml, guacamole-common/pom.xml, guacamole-ext/pom.xml, guacamole/pom.xml
The guacamole-client package build is currently failing due to parent POMs not properly resolving. This is because the parent POMs have not been updated to have the expected version suffixes, and thus can't be located at build time. This change adds the required suffixes.
=> GLEN-301: Correct version number suffixes of newly-reorganized projects.
