guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connection/ConnectionRESTService.java
guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connectiongroup/ConnectionGroupRESTService.java

GUAC-983: Move connections/groups based on parent, not parent of parent.

---

guacamole/src/main/webapp/app/textInput/directives/guacTextInput.js

GUAC-970: Reduce padding. It's too much for the poor iPad to handle.

---

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connectiongroup/ConnectionGroupRESTService.java
guacamole/src/main/webapp/app/groupList/types/GroupListItem.js
guacamole/src/main/webapp/app/index/styles/ui.css

Only query contents of connection groups if they are not balancing or we have admin permission. Fix rendering of balancing groups for non-admins.

GUAC-1010: Fix handling of balancing groups.

---

guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/client/services/guacAudio.js
guacamole/src/main/webapp/app/client/styles/menu.css
guacamole/src/main/webapp/app/client/templates/client.html

This change addresses concerns with the appearance of the menu - both with its being uselessly obscured when the keyboard is shown on iOS, and with the position of the menu header.
During testing, a regression of GUAC-882 prevented testing on IE11, and was fixed so development could continue.

GUAC-1044: Fix appearance of menu.

---

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/connectiongroup/ConnectionGroupTree.java

The *parameter* for permission filtering has been present from the beginning, but I guess I forgot to actually implement it.

GUAC-1100: Add permission filtering to tree retrieval.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/JDBCAuthenticationProviderModule.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/socket/AbstractGuacamoleSocketService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/socket/ActiveConnectionRecord.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/socket/MultiseatGuacamoleSocketService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/socket/ReservedGuacamoleSocketService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/socket/SingleSeatGuacamoleSocketService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/java/net/sourceforge/guacamole/net/auth/mysql/MySQLAuthenticationProvider.java

The concurrent use policies are the guicy reincarnation of the disallow-simultaneous / disallow-duplicate connections.

GUAC-1101: Implement concurrent use policies.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/org/glyptodon/guacamole/auth/jdbc/connectiongroup/ConnectionGroupMapper.xml

GUAC-1103: Add missing explicit typecast.

---

guacamole/src/main/webapp/app/client/clientModule.js
guacamole/src/main/webapp/app/client/controllers/clientController.js
guacamole/src/main/webapp/app/index/controllers/indexController.js
guacamole/src/main/webapp/app/index/indexModule.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js
guacamole/src/main/webapp/app/manage/controllers/manageController.js
guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
guacamole/src/main/webapp/app/manage/manageModule.js
guacamole/src/main/webapp/app/notification/services/guacNotification.js
guacamole/src/main/webapp/app/userMenu/directives/guacUserMenu.js
guacamole/src/main/webapp/app/userMenu/userMenuModule.js
guacamole/src/main/webapp/index.html

Without a dedicated service, directives with isolate scope have no access to the notification subsystem.

GUAC-1120: Move notifications into own service.

---

guacamole/src/main/webapp/app/index/config/indexRouteConfig.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionsController.js
guacamole/src/main/webapp/app/manage/controllers/manageSessionsController.js
guacamole/src/main/webapp/app/manage/controllers/manageUsersController.js
guacamole/src/main/webapp/app/manage/templates/manageConnections.html
guacamole/src/main/webapp/app/manage/templates/manageSessions.html
guacamole/src/main/webapp/app/manage/templates/manageUsers.html
guacamole/src/main/webapp/app/manage/types/ActiveTunnelWrapper.js
guacamole/src/main/webapp/app/userMenu/directives/guacUserMenu.js
guacamole/src/main/webapp/app/userMenu/styles/user-menu.css
guacamole/src/main/webapp/app/userMenu/templates/guacUserMenu.html
guacamole/src/main/webapp/translations/en_US.json

Split out session, user, and connection manage pages, rudimentary session management interface.

GUAC-1133 Started work on session management UI

---

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/TunnelRequestService.java

@karatheodory contributed changes to ```TunnelRequestService``` some time ago via #83, but other recent changes to parts of the extension API used by that class mean that these changes need modification.
I've merged his changes, while also:
1. Bringing the comment style up-to-date
2. Altering the semantics of the new functions to better fit the recent changes to the extension API

GUAC-1086: Merge TunnelRequestService changes contributed by Vasily

---

guacamole/.gitignore
guacamole/pom.xml
guacamole/src/main/webapp/app/index/indexModule.js

GUAC-1161: Pre-cache Angular templates during build.

---

guacamole/src/main/webapp/app/settings/templates/settingsPreferences.html
guacamole/src/main/webapp/translations/en_US.json

Adding a "Change Password" header between the language selection and the password form makes the preferences tab look *much* cleaner.

GUAC-1053: Add "Change Password" header.

---

guacamole/src/main/webapp/app/index/config/indexRouteConfig.js

Reject all attempts to visit '/' unless '/' is actually the home page. Users should be redirected to the true home page (without ever actually reaching '/') otherwise.

GUAC-1161: Reject attempts to visit '/' unless '/' is actually the home.

---

guacamole/src/main/webapp/lib/jquery.js

This resolves warning about deprecated ```getPreventDefault()```. The version we were using was from 2013, while 2.1.3 was released at the end of 2014.

GUAC-1170: Upgrade to jQuery 2.1.3

---

guacamole/src/main/webapp/app/login/styles/input.css

GUAC-587: Login button is a button not a field.

---

guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/LanguageResourceService.java

When merging language resources, the resource streams are not properly closed. Even assuming `readTree()` will always close the streams, one or both will not be closed if:
1. One of `existingStream` or `resourceStream` is `null`.
2. An `IOException` occurs during parsing of either stream.
This change isolates and simplifies language resource parsing such that stream closure is taken out of the purview of `addLanguageResource()`. The only function handling JSON parsing of the resource streams is `parseLanguageResource()`, which only handles one resource/stream at a time and guarantees the resource stream is closed via a `finally` block.

GUAC-587: Ensure resource streams are always closed.

---

doc/guacamole-example/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/pom.xml
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-postgresql/src/main/resources/guac-manifest.json
extensions/guacamole-auth-jdbc/pom.xml
extensions/guacamole-auth-ldap/pom.xml
extensions/guacamole-auth-ldap/src/main/resources/guac-manifest.json
extensions/guacamole-auth-noauth/pom.xml
extensions/guacamole-auth-noauth/src/main/resources/guac-manifest.json
guacamole-common-js/pom.xml
guacamole-common/pom.xml
guacamole-ext/pom.xml
guacamole/pom.xml
guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionManifest.java
guacamole/src/main/java/org/glyptodon/guacamole/net/basic/extension/ExtensionModule.java
pom.xml

GUAC-1174: Bump version numbers to 0.9.7.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-mysql/schema/002-create-admin-user.sql

The MySQL guacadmin creation script should not rely on specific IDs nor on the column order/count of `guacamole_user`. This script previously did not specify the columns used within `INSERT` for `guacamole_user`, and thus immediately started failing when new columns were added:
```console
$ cat *.sql | mysql -u root guacamole_db
ERROR 1136 (21S01) at line 256: Column count doesn't match value count at row 1
$ 
```

GUAC-1220: Fix MySQL guacadmin creation script

---

guacamole/src/main/webapp/app/settings/services/preferenceService.js

See: https://sourceforge.net/p/guacamole/discussion/1110834/thread/fc1afea8/

GUAC-1229: Default to English until language fallback issues can be resolved.

---

guacamole/src/main/webapp/app/osk/styles/osk.css
guacamole/src/main/webapp/layouts/en-us-qwerty.json
guacamole/src/main/webapp/layouts/fr-fr-azerty.json
guacamole/src/main/webapp/layouts/ru-ru-qwerty.json

OSK Super and Menu keys are stuck together.
Removed 'super' modifier on the Menu key so that these work independently and the context menu can be accessed from the Menu key.

GUAC-1245: OSK Super and Menu keys are stuck together. 

---

guacamole/src/main/webapp/translations/en.json

A change destioned for greatness.

GUAC-1323: Fix typo in error message.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/glyptodon/guacamole/auth/jdbc/tunnel/AbstractGuacamoleTunnelService.java

GUAC-1335: Properly release parent balancing groups if child acquire fails.

---

guacamole/src/main/webapp/app/index/styles/input.css

See https://bugzilla.mozilla.org/show_bug.cgi?id=1137650.

GUAC-1440: Fix rendering of textarea elements within the admin UI.

---

guacamole-common/src/main/java/org/glyptodon/guacamole/servlet/GuacamoleHTTPTunnelMap.java
guacamole/src/main/java/org/glyptodon/guacamole/net/basic/rest/auth/BasicTokenSessionMap.java

While reviewing recent changes, I noticed the following potential problems:
1. The constant put/get operations on both the session and the tunnel maps will cause excessive contention for large loads, as the map implementation will lock the entire map on **all** operations. 
2. We're not synchronizing on the map when iterating, which is against spec (http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedMap(java.util.Map)).
Switching to `ConcurrentHashMap` should solve all of the above. It won't keep things in order of access, but the overhead of having to iterate the whole map pales in comparison to the overhead of massive contention across sessions and tunnels.

GUAC-1427: Fix possible issues with concurrency.

---

extensions/guacamole-auth-ldap/README
extensions/guacamole-auth-ldap/doc/examples/exampleConfigGroup.ldif
extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/ConfigurationService.java
extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/LDAPGuacamoleProperties.java
extensions/guacamole-auth-ldap/src/main/java/org/glyptodon/guacamole/auth/ldap/connection/ConnectionService.java

These changes merge the changes from #303 (namely commit 72dddc0) plus some minor cleanup and additional documentation.

GUAC-1388: Allow LDAP role-based access control for guacConfigGroups

---

guacamole/src/main/webapp/app/client/controllers/clientController.js

We can set local clipboard data in all browsers within `keyup` events, but probably shouldn't do so unless that clipboard data likely came from pressing the keys being released. Doing otherwise would lead to the clipboard unexpectedly syncing or overwriting local clipboard data when users are simply typing.

GUAC-1480: Sync local clipboard with received data if it appears due to a keyboard shortcut.

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/JDBCAuthenticationProviderService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserModel.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java

See: apache/incubator-guacamole-client#165.

GLYP-37: Apply database "Account Restrictions" when account is required

---

guacamole/src/main/webapp/app/index/controllers/indexController.js
guacamole/src/main/webapp/index.html
guacamole/src/main/webapp/relocateParameters.js

See:
* apache/incubator-guacamole-client#156
* apache/incubator-guacamole-client#157

GLYP-38: Address issues with unexpected AngularJS behavior

---

extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/base/ModeledDirectoryObjectService.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/ModeledUser.java
extensions/guacamole-auth-jdbc/modules/guacamole-auth-jdbc-base/src/main/java/org/apache/guacamole/auth/jdbc/user/UserService.java
guacamole/src/main/webapp/app/form/directives/form.js
guacamole/src/main/webapp/app/form/templates/form.html
guacamole/src/main/webapp/app/manage/controllers/manageConnectionController.js
guacamole/src/main/webapp/app/manage/controllers/manageConnectionGroupController.js
guacamole/src/main/webapp/app/manage/controllers/manageSharingProfileController.js
guacamole/src/main/webapp/app/manage/controllers/manageUserController.js
guacamole/src/main/webapp/app/manage/templates/manageConnection.html
guacamole/src/main/webapp/app/manage/templates/manageConnectionGroup.html
guacamole/src/main/webapp/app/manage/templates/manageSharingProfile.html
guacamole/src/main/webapp/app/manage/templates/manageUser.html

See: apache/incubator-guacamole-client#158

GLYP-39: Do not allow users to edit their own account restrictions

---

guacamole/src/main/webapp/app/client/styles/display.css

See: https://issues.apache.org/jira/browse/GUACAMOLE-252pache

GLEN-103: Fix "jumping" screen within MS Edge / IE

---

guacamole-common-js/src/main/webapp/modules/Tunnel.js

See: https://issues.apache.org/jira/browse/GUACAMOLE-385

GLEN-105: Correct mimetype of HTTP tunnel write operations

---

guacamole/src/main/webapp/app/groupList/directives/guacGroupList.js
guacamole/src/main/webapp/app/groupList/directives/guacGroupListFilter.js
guacamole/src/main/webapp/app/groupList/types/GroupListItem.js
guacamole/src/main/webapp/app/manage/controllers/manageUserController.js

See: https://issues.apache.org/jira/browse/GUACAMOLE-338

GLEN-106: Always display selected connections within user editor

---

guacamole/pom.xml
guacamole/src/main/java/org/apache/guacamole/rest/auth/TokenRESTService.java
guacamole/src/main/java/org/apache/guacamole/rest/user/UserResource.java
guacamole/src/main/webapp/app/auth/authModule.js
guacamole/src/main/webapp/app/auth/service/authenticationService.js
guacamole/src/main/webapp/app/history/historyModule.js
guacamole/src/main/webapp/app/history/services/guacHistory.js
guacamole/src/main/webapp/app/settings/services/preferenceService.js
guacamole/src/main/webapp/app/settings/settingsModule.js
guacamole/src/main/webapp/app/storage/services/localStorageService.js
guacamole/src/main/webapp/index.html

See: https://issues.apache.org/jira/browse/GUACAMOLE-549

GLEN-126: Remove unnecessary use of cookies (use localStorage instead).

---

guacamole-common-js/src/main/webapp/modules/Keyboard.js

See: glyptodon/guacamole-server#152

GLEN-124: Correct keysym definition of "Print Screen" key

---

guacamole/src/main/webapp/app/navigation/services/userPageService.js

See: https://issues.apache.org/jira/browse/GUACAMOLE-508

GLEN-129: Automatically connect only if user lacks access to settings
